"""VietQR Python encoder — byte-identical to the SPA JS encoder.

The two vectors below were generated by running
``src/utils/vietqr.js encodeVietQR`` (node) — they are the shared contract:
if this Python port ever drifts, the backend snapshot QR would stop matching
what bank apps expect.
"""

from gege_hr.gege_hr.utils import vietqr as V

# node -e "…encodeVietQR({bankBin:'970422',accountNumber:'0029999975666',
#   amount:1449031.1, description:'LUONG-052026-HR-EMP-00010'})"
VECTOR_DYNAMIC = (
    "00020101021238570010A0000007270127000697042201130029999975666"
    "0208QRIBFTTA5303704540714490315802VN62250821LUONG052026HREMP0001063048772"
)

# Static (no amount): encodeVietQR({bankBin:'970436',accountNumber:'0071000812345'})
VECTOR_STATIC = (
    "00020101021138570010A00000072701270006970436011300710008123450208QRIBFTTA53037045802VN6304AC99"
)


def test_matches_js_dynamic_vector():
    out = V.encode_vietqr(
        "970422", "0029999975666", amount=1449031.1, description="LUONG-052026-HR-EMP-00010"
    )
    assert out == VECTOR_DYNAMIC


def test_matches_js_static_vector():
    assert V.encode_vietqr("970436", "0071000812345") == VECTOR_STATIC


def test_crc_verify_ok_and_bad():
    assert V.verify_vietqr(VECTOR_DYNAMIC) is True
    assert V.verify_vietqr(VECTOR_DYNAMIC[:-1] + "0") is False
    assert V.verify_vietqr("") is False


def test_amount_floored_to_int():
    out = V.encode_vietqr("970422", "0029999975666", amount=1449031.9)
    assert "54071449031" in out  # 7 chars tag54 + int amount, no decimals
    assert V.verify_vietqr(out)


def test_remove_accents():
    assert V.remove_accents("Nguyễn Tiến Dũng") == "NGUYEN TIEN DUNG"
    assert V.remove_accents("LUONG-05/2026 Đ") == "LUONG052026 D"
    assert V.remove_accents("") == ""
